application: %(name)s
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:

- url: /static
  static_dir: static

- url: /stylesheets
  static_dir: static/stylesheets

- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js

- url: .*
  script: main.app

